# General
SIMULATION_AMOUNT = 100

# Predator
PREDATOR_LOCATION_LOWER_BOUND = 0
PREDATOR_LOCATION_UPPER_BOUND = 0

PREDATOR_HEALTH_LOWER_BOUND = 100
PREDATOR_HEALTH_UPPER_BOUND = 100

PREDATOR_STAMINA_LOWER_BOUND = 0
PREDATOR_STAMINA_UPPER_BOUND = 100

PREDATOR_BASE_ATTACK_POWER = 1

PREDATOR_NAME = "Predator"

PREDATOR_EVOLUTION_AMOUNT = 10

# Prey
PREY_LOCATION_LOWER_BOUND = 0
PREY_LOCATION_UPPER_BOUND = 100

PREY_HEALTH_LOWER_BOUND = 100
PREY_HEALTH_UPPER_BOUND = 100

PREY_STAMINA_LOWER_BOUND = 0
PREY_STAMINA_UPPER_BOUND = 100

PREY_BASE_ATTACK_POWER = 1

PREY_NAME = "Prey"

PREY_EVOLUTION_AMOUNT = 5

# Moves
CRAWL_STAMINA_USAGE = 1
CRAWL_SPEED = 1
STAMINA_REQUIRED_TO_CRAWL = 1

HOP_STAMINA_USAGE = 2
HOP_SPEED = 3
STAMINA_REQUIRED_TO_HOP = 21
LEG_AMOUNT_REQUIRED_TO_HOP = 1

WALK_STAMINA_USAGE = 2
WALK_SPEED = 4
STAMINA_REQUIRED_TO_WALK = 41
LEG_AMOUNT_REQUIRED_TO_WALK = 2

RUN_STAMINA_USAGE = 4
RUN_SPEED = 6
STAMINA_REQUIRED_TO_RUN = 61
LEG_AMOUNT_REQUIRED_TO_RUN = 2

FLY_STAMINA_USAGE = 4
FLY_SPEED = 8
STAMINA_REQUIRED_TO_FLY = 81
WING_AMOUNT_REQUIRED_TO_FLY = 2

# Evolutions
SMALL_CLAWS_DAMAGE_MULTIPLIER = 2
MEDIUM_CLAWS_DAMAGE_MULTIPLIER = 3
BIG_CLAWS_DAMAGE_MULTIPLIER = 4

SHARP_TEETH_ADDED_DAMAGE = 3
SHARPER_TEETH_ADDED_DAMAGE = 6
SHARPEST_TEETH_ADDED_DAMAGE = 9
